# Generated by Django 4.1.13 on 2024-10-31 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialize_main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observed',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='+77777777777', max_length=12),
        ),
        migrations.AlterField(
            model_name='games',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='Иван', max_length=150),
        ),
    ]
