# Generated by Django 4.1.13 on 2024-11-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialize_main', '0002_remove_observed_phone_number_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='second_name',
            field=models.CharField(blank=True, default='Иванов', max_length=150),
        ),
    ]
